-- MySQL Script generated by MySQL Workbench
-- Sun May  5 15:48:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Photos` (
  `id` INT NOT NULL,
  `image_url` VARCHAR(45) NULL,
  `user_id` INT NULL,
  `created_at` TIMESTAMP NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `Photo_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `Photo_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comments` (
  `id` INT NOT NULL,
  `user_id` INT NULL,
  `photo_id` INT NULL,
  `comment_test` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `user_comment_idx` (`user_id` ASC) VISIBLE,
  INDEX `photo_comment_idx` (`photo_id` ASC) VISIBLE,
  CONSTRAINT `user_comment`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `photo_comment`
    FOREIGN KEY (`photo_id`)
    REFERENCES `mydb`.`Photos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Likes` (
  `user_id` INT NOT NULL,
  `photo_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT now(),
  PRIMARY KEY (`user_id`, `photo_id`),
  INDEX `like_photo_idx` (`photo_id` ASC) VISIBLE,
  CONSTRAINT `like_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `like_photo`
    FOREIGN KEY (`photo_id`)
    REFERENCES `mydb`.`Photos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tags` (
  `tag_id` INT NOT NULL,
  `tag_name` VARCHAR(45) NULL,
  PRIMARY KEY (`tag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Follows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Follows` (
  `followr_id` INT NOT NULL,
  `followee_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT now(),
  PRIMARY KEY (`followr_id`, `followee_id`),
  INDEX `followee_user_idx` (`followee_id` ASC) VISIBLE,
  CONSTRAINT `follower_user`
    FOREIGN KEY (`followr_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `followee_user`
    FOREIGN KEY (`followee_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Photo_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Photo_tag` (
  `photo_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`photo_id`, `tag_id`),
  INDEX `phototag_tag_idx` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `phototag_photo`
    FOREIGN KEY (`photo_id`)
    REFERENCES `mydb`.`Photos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `phototag_tag`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mydb`.`Tags` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
